using Kaitai;

namespace KaitaiTtf.Os2
{
    public class UnicodeRange : KaitaiStruct
    {
        public static UnicodeRange FromFile(string fileName)
        {
            return new UnicodeRange(new KaitaiStream(fileName));
        }

        public UnicodeRange(KaitaiStream p__io, Os2 p__parent = null, Ttf p__root = null) : base(p__io)
        {
            m_parent = p__parent;
            m_root = p__root;
            _read();
        }
        private void _read()
        {
            _basicLatin = m_io.ReadBitsIntBe(1) != 0;
            _latin1Supplement = m_io.ReadBitsIntBe(1) != 0;
            _latinExtendedA = m_io.ReadBitsIntBe(1) != 0;
            _latinExtendedB = m_io.ReadBitsIntBe(1) != 0;
            _ipaExtensions = m_io.ReadBitsIntBe(1) != 0;
            _spacingModifierLetters = m_io.ReadBitsIntBe(1) != 0;
            _combiningDiacriticalMarks = m_io.ReadBitsIntBe(1) != 0;
            _basicGreek = m_io.ReadBitsIntBe(1) != 0;
            _greekSymbolsAndCoptic = m_io.ReadBitsIntBe(1) != 0;
            _cyrillic = m_io.ReadBitsIntBe(1) != 0;
            _armenian = m_io.ReadBitsIntBe(1) != 0;
            _basicHebrew = m_io.ReadBitsIntBe(1) != 0;
            _hebrewExtended = m_io.ReadBitsIntBe(1) != 0;
            _basicArabic = m_io.ReadBitsIntBe(1) != 0;
            _arabicExtended = m_io.ReadBitsIntBe(1) != 0;
            _devanagari = m_io.ReadBitsIntBe(1) != 0;
            _bengali = m_io.ReadBitsIntBe(1) != 0;
            _gurmukhi = m_io.ReadBitsIntBe(1) != 0;
            _gujarati = m_io.ReadBitsIntBe(1) != 0;
            _oriya = m_io.ReadBitsIntBe(1) != 0;
            _tamil = m_io.ReadBitsIntBe(1) != 0;
            _telugu = m_io.ReadBitsIntBe(1) != 0;
            _kannada = m_io.ReadBitsIntBe(1) != 0;
            _malayalam = m_io.ReadBitsIntBe(1) != 0;
            _thai = m_io.ReadBitsIntBe(1) != 0;
            _lao = m_io.ReadBitsIntBe(1) != 0;
            _basicGeorgian = m_io.ReadBitsIntBe(1) != 0;
            _georgianExtended = m_io.ReadBitsIntBe(1) != 0;
            _hangulJamo = m_io.ReadBitsIntBe(1) != 0;
            _latinExtendedAdditional = m_io.ReadBitsIntBe(1) != 0;
            _greekExtended = m_io.ReadBitsIntBe(1) != 0;
            _generalPunctuation = m_io.ReadBitsIntBe(1) != 0;
            _superscriptsAndSubscripts = m_io.ReadBitsIntBe(1) != 0;
            _currencySymbols = m_io.ReadBitsIntBe(1) != 0;
            _combiningDiacriticalMarksForSymbols = m_io.ReadBitsIntBe(1) != 0;
            _letterlikeSymbols = m_io.ReadBitsIntBe(1) != 0;
            _numberForms = m_io.ReadBitsIntBe(1) != 0;
            _arrows = m_io.ReadBitsIntBe(1) != 0;
            _mathematicalOperators = m_io.ReadBitsIntBe(1) != 0;
            _miscellaneousTechnical = m_io.ReadBitsIntBe(1) != 0;
            _controlPictures = m_io.ReadBitsIntBe(1) != 0;
            _opticalCharacterRecognition = m_io.ReadBitsIntBe(1) != 0;
            _enclosedAlphanumerics = m_io.ReadBitsIntBe(1) != 0;
            _boxDrawing = m_io.ReadBitsIntBe(1) != 0;
            _blockElements = m_io.ReadBitsIntBe(1) != 0;
            _geometricShapes = m_io.ReadBitsIntBe(1) != 0;
            _miscellaneousSymbols = m_io.ReadBitsIntBe(1) != 0;
            _dingbats = m_io.ReadBitsIntBe(1) != 0;
            _cjkSymbolsAndPunctuation = m_io.ReadBitsIntBe(1) != 0;
            _hiragana = m_io.ReadBitsIntBe(1) != 0;
            _katakana = m_io.ReadBitsIntBe(1) != 0;
            _bopomofo = m_io.ReadBitsIntBe(1) != 0;
            _hangulCompatibilityJamo = m_io.ReadBitsIntBe(1) != 0;
            _cjkMiscellaneous = m_io.ReadBitsIntBe(1) != 0;
            _enclosedCjkLettersAndMonths = m_io.ReadBitsIntBe(1) != 0;
            _cjkCompatibility = m_io.ReadBitsIntBe(1) != 0;
            _hangul = m_io.ReadBitsIntBe(1) != 0;
            _reservedForUnicodeSubranges1 = m_io.ReadBitsIntBe(1) != 0;
            _reservedForUnicodeSubranges2 = m_io.ReadBitsIntBe(1) != 0;
            _cjkUnifiedIdeographs = m_io.ReadBitsIntBe(1) != 0;
            _privateUseArea = m_io.ReadBitsIntBe(1) != 0;
            _cjkCompatibilityIdeographs = m_io.ReadBitsIntBe(1) != 0;
            _alphabeticPresentationForms = m_io.ReadBitsIntBe(1) != 0;
            _arabicPresentationFormsA = m_io.ReadBitsIntBe(1) != 0;
            _combiningHalfMarks = m_io.ReadBitsIntBe(1) != 0;
            _cjkCompatibilityForms = m_io.ReadBitsIntBe(1) != 0;
            _smallFormVariants = m_io.ReadBitsIntBe(1) != 0;
            _arabicPresentationFormsB = m_io.ReadBitsIntBe(1) != 0;
            _halfwidthAndFullwidthForms = m_io.ReadBitsIntBe(1) != 0;
            _specials = m_io.ReadBitsIntBe(1) != 0;
            m_io.AlignToByte();
            _reserved = m_io.ReadBytes(7);
        }
        private bool _basicLatin;
        private bool _latin1Supplement;
        private bool _latinExtendedA;
        private bool _latinExtendedB;
        private bool _ipaExtensions;
        private bool _spacingModifierLetters;
        private bool _combiningDiacriticalMarks;
        private bool _basicGreek;
        private bool _greekSymbolsAndCoptic;
        private bool _cyrillic;
        private bool _armenian;
        private bool _basicHebrew;
        private bool _hebrewExtended;
        private bool _basicArabic;
        private bool _arabicExtended;
        private bool _devanagari;
        private bool _bengali;
        private bool _gurmukhi;
        private bool _gujarati;
        private bool _oriya;
        private bool _tamil;
        private bool _telugu;
        private bool _kannada;
        private bool _malayalam;
        private bool _thai;
        private bool _lao;
        private bool _basicGeorgian;
        private bool _georgianExtended;
        private bool _hangulJamo;
        private bool _latinExtendedAdditional;
        private bool _greekExtended;
        private bool _generalPunctuation;
        private bool _superscriptsAndSubscripts;
        private bool _currencySymbols;
        private bool _combiningDiacriticalMarksForSymbols;
        private bool _letterlikeSymbols;
        private bool _numberForms;
        private bool _arrows;
        private bool _mathematicalOperators;
        private bool _miscellaneousTechnical;
        private bool _controlPictures;
        private bool _opticalCharacterRecognition;
        private bool _enclosedAlphanumerics;
        private bool _boxDrawing;
        private bool _blockElements;
        private bool _geometricShapes;
        private bool _miscellaneousSymbols;
        private bool _dingbats;
        private bool _cjkSymbolsAndPunctuation;
        private bool _hiragana;
        private bool _katakana;
        private bool _bopomofo;
        private bool _hangulCompatibilityJamo;
        private bool _cjkMiscellaneous;
        private bool _enclosedCjkLettersAndMonths;
        private bool _cjkCompatibility;
        private bool _hangul;
        private bool _reservedForUnicodeSubranges1;
        private bool _reservedForUnicodeSubranges2;
        private bool _cjkUnifiedIdeographs;
        private bool _privateUseArea;
        private bool _cjkCompatibilityIdeographs;
        private bool _alphabeticPresentationForms;
        private bool _arabicPresentationFormsA;
        private bool _combiningHalfMarks;
        private bool _cjkCompatibilityForms;
        private bool _smallFormVariants;
        private bool _arabicPresentationFormsB;
        private bool _halfwidthAndFullwidthForms;
        private bool _specials;
        private byte[] _reserved;
        private Ttf m_root;
        private Os2 m_parent;
        public bool BasicLatin => _basicLatin;
        public bool Latin1Supplement => _latin1Supplement;
        public bool LatinExtendedA => _latinExtendedA;
        public bool LatinExtendedB => _latinExtendedB;
        public bool IpaExtensions => _ipaExtensions;
        public bool SpacingModifierLetters => _spacingModifierLetters;
        public bool CombiningDiacriticalMarks => _combiningDiacriticalMarks;
        public bool BasicGreek => _basicGreek;
        public bool GreekSymbolsAndCoptic => _greekSymbolsAndCoptic;
        public bool Cyrillic => _cyrillic;
        public bool Armenian => _armenian;
        public bool BasicHebrew => _basicHebrew;
        public bool HebrewExtended => _hebrewExtended;
        public bool BasicArabic => _basicArabic;
        public bool ArabicExtended => _arabicExtended;
        public bool Devanagari => _devanagari;
        public bool Bengali => _bengali;
        public bool Gurmukhi => _gurmukhi;
        public bool Gujarati => _gujarati;
        public bool Oriya => _oriya;
        public bool Tamil => _tamil;
        public bool Telugu => _telugu;
        public bool Kannada => _kannada;
        public bool Malayalam => _malayalam;
        public bool Thai => _thai;
        public bool Lao => _lao;
        public bool BasicGeorgian => _basicGeorgian;
        public bool GeorgianExtended => _georgianExtended;
        public bool HangulJamo => _hangulJamo;
        public bool LatinExtendedAdditional => _latinExtendedAdditional;
        public bool GreekExtended => _greekExtended;
        public bool GeneralPunctuation => _generalPunctuation;
        public bool SuperscriptsAndSubscripts => _superscriptsAndSubscripts;
        public bool CurrencySymbols => _currencySymbols;
        public bool CombiningDiacriticalMarksForSymbols => _combiningDiacriticalMarksForSymbols;
        public bool LetterlikeSymbols => _letterlikeSymbols;
        public bool NumberForms => _numberForms;
        public bool Arrows => _arrows;
        public bool MathematicalOperators => _mathematicalOperators;
        public bool MiscellaneousTechnical => _miscellaneousTechnical;
        public bool ControlPictures => _controlPictures;
        public bool OpticalCharacterRecognition => _opticalCharacterRecognition;
        public bool EnclosedAlphanumerics => _enclosedAlphanumerics;
        public bool BoxDrawing => _boxDrawing;
        public bool BlockElements => _blockElements;
        public bool GeometricShapes => _geometricShapes;
        public bool MiscellaneousSymbols => _miscellaneousSymbols;
        public bool Dingbats => _dingbats;
        public bool CjkSymbolsAndPunctuation => _cjkSymbolsAndPunctuation;
        public bool Hiragana => _hiragana;
        public bool Katakana => _katakana;
        public bool Bopomofo => _bopomofo;
        public bool HangulCompatibilityJamo => _hangulCompatibilityJamo;
        public bool CjkMiscellaneous => _cjkMiscellaneous;
        public bool EnclosedCjkLettersAndMonths => _enclosedCjkLettersAndMonths;
        public bool CjkCompatibility => _cjkCompatibility;
        public bool Hangul => _hangul;
        public bool ReservedForUnicodeSubranges1 => _reservedForUnicodeSubranges1;
        public bool ReservedForUnicodeSubranges2 => _reservedForUnicodeSubranges2;
        public bool CjkUnifiedIdeographs => _cjkUnifiedIdeographs;
        public bool PrivateUseArea => _privateUseArea;
        public bool CjkCompatibilityIdeographs => _cjkCompatibilityIdeographs;
        public bool AlphabeticPresentationForms => _alphabeticPresentationForms;
        public bool ArabicPresentationFormsA => _arabicPresentationFormsA;
        public bool CombiningHalfMarks => _combiningHalfMarks;
        public bool CjkCompatibilityForms => _cjkCompatibilityForms;
        public bool SmallFormVariants => _smallFormVariants;
        public bool ArabicPresentationFormsB => _arabicPresentationFormsB;
        public bool HalfwidthAndFullwidthForms => _halfwidthAndFullwidthForms;
        public bool Specials => _specials;
        public byte[] Reserved => _reserved;
        public Ttf M_Root => m_root;
        public Os2 M_Parent => m_parent;
    }
}
